import numpy as np
from enum import IntEnum

# Court geometry (meters)
COURT_LENGTH = 18.0       # x-axis: -9 to +9
COURT_WIDTH = 9.0         # y-axis: -4.5 to +4.5
COURT_HALF = COURT_LENGTH / 2   # 9.0
COURT_HALF_W = COURT_WIDTH / 2  # 4.5
NET_HEIGHT = 2.43         # men's net
ATTACK_LINE = 3.0         # distance from net
BALL_RADIUS = 0.103
BALL_MASS = 0.270

# Team A plays x > 0, team B plays x < 0
TEAM_A_SIDE = 1
TEAM_B_SIDE = -1

# Set zone: target for back-row passes (meters from net, centered)
SET_ZONE_CENTER = np.array([1.5, 0.0, 2.0])  # in team A coords; mirror for B
SET_ZONE_RADIUS = 1.2  # acceptable pass radius around set zone center

# Attack window: valid set target zone
ATTACK_WINDOW_X_RANGE = (0.3, 1.5)   # distance from net
ATTACK_WINDOW_Z_RANGE = (2.3, 3.8)   # height range

# Physics
GRAVITY = 9.81
MAGNUS_COEFF = 0.00029   # k in F = k*(omega x v), tuned for volleyball

# Timestep
SIM_DT = 1.0 / 120.0    # 120 Hz physics
CONTROL_DT = 1.0 / 30.0  # 30 Hz policy (4 physics steps per control step)
PHYSICS_STEPS_PER_CONTROL = int(CONTROL_DT / SIM_DT)

# Episode limits
MAX_RALLY_STEPS = 1000   # ~33 seconds at 30Hz before forced termination

# Roles
class Role(IntEnum):
    SETTER = 0
    OH_FRONT = 1
    OH_BACK = 2
    MB_FRONT = 3
    MB_BACK = 4
    OPP_FRONT = 5
    OPP_BACK = 6
    LIBERO = 7

class Phase(IntEnum):
    SERVE = 0
    RECEIVE = 1
    SET = 2
    ATTACK = 3
    BLOCKED = 4
    FREE_BALL = 5
    DEAD = 6  # ball hit floor or out

# Number of players per team
PLAYERS_PER_TEAM = 6
TOTAL_PLAYERS = 12

# Contact limit per team possession
MAX_TEAM_TOUCHES = 3

# Default starting positions for team A (x > 0 side)
# Rotation 0: P1=back-right, P2=front-right, P3=front-middle, P4=front-left, P5=back-left, P6=back-middle
# x increases away from net; y is lateral; z is up
TEAM_A_START_POSITIONS = [
    # (x, y) pairs for positions 1-6
    (6.5, -2.0),   # P1: back-right (server / OPP_BACK)
    (2.5, -2.0),   # P2: front-right (OPP_FRONT)
    (2.5,  0.0),   # P3: front-middle (MB_FRONT)
    (2.5,  2.0),   # P4: front-left (OH_FRONT)
    (6.5,  2.0),   # P5: back-left (OH_BACK)
    (6.5,  0.0),   # P6: back-middle (LIBERO / MB_BACK)
]

TEAM_B_START_POSITIONS = [
    (-6.5,  2.0),  # P7: mirror of P1
    (-2.5,  2.0),  # P8
    (-2.5,  0.0),  # P9
    (-2.5, -2.0),  # P10
    (-6.5, -2.0),  # P11
    (-6.5,  0.0),  # P12
]

START_HEIGHT = 1.31  # torso (freejoint) z so feet just touch ground (foot bottom = root - 1.305m)

# Role assignment per position (rotation 0, 5-1 formation)
# Indices: position in TEAM_*_START_POSITIONS
TEAM_ROLE_ASSIGNMENT = [
    Role.OPP_BACK,    # P0 (position 1)
    Role.OPP_FRONT,   # P1 (position 2)
    Role.MB_FRONT,    # P2 (position 3)
    Role.OH_FRONT,    # P3 (position 4)
    Role.OH_BACK,     # P4 (position 5)
    Role.LIBERO,      # P5 (position 6 / back-middle)
]
# Setter is not in the list above because in a 5-1 the setter occupies P1 in
# one rotation and P6 in another. We handle setter specialization via role
# indicator in obs, not by removing a position slot. For initial training, P2
# (position 2) is designated setter and uses SETTER role.
TEAM_ROLE_ASSIGNMENT[1] = Role.SETTER

# Player body joint names (generated by scene_builder; stored here for reference)
PLAYER_JOINT_NAMES = [
    "root",                                      # freejoint (7 qpos: pos + quat)
    "lumbar_x", "lumbar_y", "lumbar_z",
    "left_shoulder_x", "left_shoulder_y", "left_shoulder_z",
    "left_elbow", "left_wrist",
    "right_shoulder_x", "right_shoulder_y", "right_shoulder_z",
    "right_elbow", "right_wrist",
    "left_hip_x", "left_hip_y", "left_hip_z",
    "left_knee", "left_ankle_x", "left_ankle_y",
    "right_hip_x", "right_hip_y", "right_hip_z",
    "right_knee", "right_ankle_x", "right_ankle_y",
]

# DOF per player (freejoint = 7 qpos / 6 qvel; rest = 1 each)
PLAYER_QPOS_DIM = 7 + 3 + 5 + 5 + 3 + 3 + 3 + 3  # = 32
PLAYER_QVEL_DIM = 6 + 3 + 5 + 5 + 3 + 3 + 3 + 3  # = 31 (freejoint vel = 6)

# Actuator count per player (all hinge joints, no freejoint actuator)
PLAYER_ACT_DIM = 3 + 5 + 5 + 3 + 3 + 3 + 3        # = 25

# Observation dimensions
OBS_BALL = 9              # pos(3) + vel(3) + spin(3)
OBS_SELF = PLAYER_QPOS_DIM + PLAYER_QVEL_DIM  # own joint state
OBS_TEAMMATES = 5 * 9    # 5 teammates: root pos(3) + vel(3) + facing(3)
OBS_OPPONENTS = 6 * 6    # 6 opponents: root pos(3) + vel(3)
OBS_PHASE = len(Phase)   # one-hot
OBS_ROLE = len(Role)     # one-hot
OBS_SCORE = 2            # (own team score, opp score) normalised
OBS_TOUCH_COUNT = 2      # (own team touches this possession, opp touches)

LOCAL_OBS_DIM = (
    OBS_BALL + OBS_SELF + OBS_TEAMMATES + OBS_OPPONENTS +
    OBS_PHASE + OBS_ROLE + OBS_SCORE + OBS_TOUCH_COUNT
)

# Centralized critic global obs
GLOBAL_OBS_DIM = (
    OBS_BALL +
    TOTAL_PLAYERS * (PLAYER_QPOS_DIM + PLAYER_QVEL_DIM) +
    OBS_PHASE + OBS_SCORE + OBS_TOUCH_COUNT
)
